<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Professional Trading Checklist</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            background-color: #f8f9fa;
            color: #2c3e50;
            padding: 2rem;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        h1 {
            text-align: center;
            margin-bottom: 2rem;
            font-size: 2.5rem;
            color: #2c3e50;
        }

        .line-entry {
            background: white;
            border-radius: 10px;
            padding: 1rem;
            margin-bottom: 1rem;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            border-left: 5px solid #3498db;
        }

        .line-entry strong {
            color: #3498db;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Professional Trading Checklist</h1>
        <h2>Saved Checklists</h2>
        <div id="resultsContainer"></div>
    </div>

    <script>
        let checklists = JSON.parse(localStorage.getItem('tradingChecklists')) || [];

        function updateResultsContainer() {
            const container = document.getElementById('resultsContainer');
            container.innerHTML = '';
            
            checklists.forEach(checklist => {
                const entry = document.createElement('div');
                entry.className = 'line-entry';
                entry.innerHTML = `
                    <p><strong>Timestamp:</strong> ${checklist.timestamp}</p>
                    <p><strong>Sessions:</strong> ${checklist.sessions.join(', ')}</p>
                    <p><strong>Market Analysis:</strong> ${checklist.marketAnalysis.join('; ')}</p>
                    <p><strong>Current Position:</strong> ${checklist.currentPosition.join('; ')}</p>
                    <p><strong>Entries:</strong> ${checklist.entries.join('; ')}</p>
                    <p><strong>Risk Management:</strong> ${checklist.riskManagement.join('; ')}</p>
                    <p><strong>Conclusion:</strong> ${checklist.conclusion.join('; ')}</p>
                `;
                container.appendChild(entry);
            });
        }

        updateResultsContainer();
    </script>
</body>
</html>

